# Generated by Django 4.1.7 on 2023-03-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='autistic',
        ),
    ]
