# Generated by Django 4.1.7 on 2023-03-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
