# Generated by Django 4.1.7 on 2023-03-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_registration_patient_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration_patient',
        ),
    ]
