# Generated by Django 4.1.7 on 2023-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_alter_patient_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DoB',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
